### ISSUE TITLE
Atualizar README do ms-clientes.

### ISSUE THREAD

**Issue by lgshogun** [redmasters/alice#16]
Necessária atualização do README do projeto em ruby, mas apenas pra Icaro poder aprender um pouco mais.

**Comment by Icaroicro** [comment]
# API Clientes

#### Uma API para os Clientes do projeto Alice, que terão um relacionamento com o estoque.

## :books: Informações:

* Ruby 3.0.2
* Rails 7.0.7

### :question: Como Rodar:

1. Clone esse repositório: https://github.com/redmasters/alice
```
git clone https://github.com/redmasters/alice.git
```
2. Entre na pasta do repositório: `alice/backend`
4. Mude a branch para `12-criação-do-projeto-api-clientes-on-rails`.
 ```
 git checkout 12-criação-do-projeto-api-clientes-on-rails
 ```
5. Entre na pasta do ms-clientes: `alice/backend/ms-clientes`.
6. Por fim, rode o servidor com:
```
rails s
```

### :gear: Ferramentas:
* VS Code.
*  Git.
*  Ruby.
* Rails.
*  PostgreSQL.
