### ISSUE TITLE
Aprofundando no MVC do Rails

### ISSUE THREAD

**Issue by lgshogun** [redmasters/alice#21]
Conhecendo mais sobre o MVC do bundle criado do Ruby on Rails.

**Comment by Icaroicro** [comment]
[MUITO BOMMMMMMMMM](https://www.cursoemvideo.com/curso/curso-de-git-e-github/aulas/aulas-de-git-e-github/modulos/git-branches-de-forma-facil-e-com-exemplo-curso-de-git-e-github/)

**Comment by lgshogun** [comment]
Terminado antes
